version: '3'
  
services:
    mariadb:
        image: mariadb:inc
        volumes:
                - maria:/var/lib/mysql
        restart: always
        environment:
            MARIA_LOGIN: "${MARIA_LOGIN}"
            MARIA_PASS: "${MARIA_PASS}"
        ports: 
            - "3306"
        build:
            context: ./mariadb
            dockerfile: Dockerfile 
        networks:
            vpcbr:
        env_file: .env
               

    wordpress:
        depends_on:
            - mariadb
        image: wordpress:inc
        volumes:
            - wp:/wordpress
        restart: always
        environment:
            WP_LOGIN: "${WP_LOGIN}"
            WP_PASS: "${WP_PASS}"
            WPU_1LOGIN: "${WPU_1LOGIN}"
            WPU_1PASS: "${WPU_1PASS}"
            MARIA_LOGIN: "${MARIA_LOGIN}"
            MARIA_PASS: "${MARIA_PASS}"
        ports:
            - "5000"
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        networks:
            vpcbr:
        env_file: .env
    nginx:
        image: nginx:inc
        restart: always
        depends_on:
            - wordpress
        ports:
                - "443:443"
        volumes:
            - wp:/var/www/wordpress
        build:
            context: ./nginx
            dockerfile: Dockerfile
        networks:
            vpcbr:
        extra_hosts:
            - "demadelei.42.fr:127.0.0.1"
        env_file: .env

networks:
    vpcbr:
        driver: bridge

volumes: 
        maria:
                driver_opts:
                        type: none
                        o: bind
                        device: /root/data/maria
        wp:
                driver_opts:
                        type: none
                        o: bind
                        device:  /root/data/wp
                      
