CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'dmadelei'@'localhost' IDENTIFIED by '11';
GRANT ALL PRIVILEGES ON *.* TO 'dmadelei'@'localhost' IDENTIFIED BY '11';
CREATE USER IF NOT EXISTS 'dmadelei'@'%' IDENTIFIED by '11';
GRANT ALL PRIVILEGES ON *.* TO 'dmadelei'@'%' IDENTIFIED BY '11';
FLUSH PRIVILEGES;
